### ISSUE TITLE
关于web component上手指南疑问

### ISSUE THREAD

**Issue by baixiaoyu2997** [Shenfq/blog#1]
你好，看了你的文章，关于这[块](https://blog.shenfq.com/posts/2021/Web%20Components%20%E4%B8%8A%E6%89%8B%E6%8C%87%E5%8D%97.html#%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E6%96%B0%E7%9A%84-html-%E6%A0%87%E7%AD%BE
)有个疑问想请教下：
这里创建自定义元素的时候，如果我的js文件在自定义元素之前，web component虽然也创建了，但是无法获取name属性，导致输出还是`Hello User Name`。

这是为什么呢？

**Comment by Shenfq** [comment]
要不加微信沟通下，我的微信号：shenfq77
