### ISSUE TITLE
您好，新版本Pagic无法安装。

### ISSUE THREAD

**Issue by rainzee** [Shenfq/blog#2]
我不是很理解Deno的依赖管理，我使用官网安装。目前得到这些
<img width="749" alt="截屏2022-03-24 下午1 07 40" src="https://user-images.githubusercontent.com/4585440/159846341-8591d4de-bacf-4274-9e33-d7b9c60dabbe.png">
。

**Comment by Shenfq** [comment]
可能是 pagic 和 react 不同版本类型不兼容，你可以在 pagic 提个 issue 问一下

**Comment by rainzee** [comment]
我已经在官方仓库提了，但是目前作者好像已经有一段时间没有迭代维护了，目前还没有回应，这种依赖问题可以通过手动来解决吗？我尝试过下载源码安装，还是一样的结果，似乎Demo是从网络拉取依赖。
